/**
 * HTTPS tunnel for Bakong MD5 relay (Bakong blocks Vercel IPs).
 * Uses running ngrok (port 4040) or localtunnel.
 */
import fs from 'fs'
import path from 'path'

export async function detectNgrokUrl() {
  try {
    const res = await fetch('http://127.0.0.1:4040/api/tunnels', { signal: AbortSignal.timeout(2000) })
    if (!res.ok) return ''
    const json = await res.json()
    const tunnels = json.tunnels || []
    const https =
      tunnels.find((t) => t.public_url?.startsWith('https://')) ||
      tunnels.find((t) => String(t.proto).includes('https'))
    return String(https?.public_url || '').trim().replace(/\/$/, '')
  } catch {
    return ''
  }
}

export function writeRelayArtifacts(root, relayUrl) {
  const url = String(relayUrl || '').trim().replace(/\/$/, '')
  if (!url.startsWith('https://')) return false

  const autoJs = path.join(root, 'standalone', 'relay.auto.js')
  fs.writeFileSync(
    autoJs,
    `/** Auto-generated by npm run relay — paste this URL on Vercel if needed */\nwindow.DYNA_RELAY_AUTO = ${JSON.stringify({ relayUrl: url })};\n`,
    'utf8',
  )

  for (const name of ['bakong.config.local.js']) {
    const cfgPath = path.join(root, 'standalone', name)
    if (!fs.existsSync(cfgPath)) continue
    let text = fs.readFileSync(cfgPath, 'utf8')
    if (/^\s*relayUrl:\s*['"]/m.test(text)) {
      text = text.replace(/^\s*relayUrl:\s*['"][^'"]*['"]/m, `  relayUrl: '${url}'`)
    } else {
      text = text.replace(
        /window\.DYNA_BAKONG_CONFIG\s*=\s*\{/,
        `window.DYNA_BAKONG_CONFIG = {\n  relayUrl: '${url}',`,
      )
    }
    fs.writeFileSync(cfgPath, text)
  }

  return true
}

export async function startPaymentTunnel({ port, root }) {
  const ngrok = await detectNgrokUrl()
  if (ngrok) {
    writeRelayArtifacts(root, ngrok)
    return { url: ngrok, kind: 'ngrok', close: async () => {} }
  }

  let lt
  try {
    const mod = await import('localtunnel')
    lt = mod.default || mod
  } catch {
    throw new Error('localtunnel not installed — run: npm install')
  }

  const tunnel = await lt({ port, local_host: '127.0.0.1' })
  const url = String(tunnel.url || '').replace(/\/$/, '')
  writeRelayArtifacts(root, url)

  return {
    url,
    kind: 'localtunnel',
    close: () =>
      new Promise((resolve) => {
        tunnel.close()
        resolve()
      }),
  }
}

export function printRelayBanner(url, port) {
  console.log('')
  console.log('  ═══════════════════════════════════════════════════════')
  console.log('  PAYMENT RELAY — Bakong works through this URL')
  console.log('  ═══════════════════════════════════════════════════════')
  console.log('')
  console.log(`  ${url}`)
  console.log('')
  console.log('  Option A — Share this link as your shop (payments work):')
  console.log(`    ${url}/index.html`)
  console.log('')
  console.log('  Option B — Keep Vercel site, paste URL once:')
  console.log('    Top up → yellow box → Relay URL → Save relay')
  console.log('    (or Advanced → Relay URL)')
  console.log('')
  console.log(`  Local: http://127.0.0.1:${port}/index.html`)
  console.log('  Keep this window open while customers pay.')
  console.log('')
}
